#!/bin/bash

#Translation
export TEXTDOMAINDIR="/usr/share/locale"
export TEXTDOMAIN=biglinux-settings-gnome

windowID="$(xprop -root '\t$0' _NET_ACTIVE_WINDOW | cut -f 2)"

> "$HOME/.config/browser-brave-disable-ad"

if [ "$1" != "quiet" ]; then
    yad --title="$TITLE" --width=390 --image="dialog-warning" --attach="$windowID" --text=$"Se estiver utilizando algum navegador, reinicie-o para aplicar as alterações." --button=OK:0
fi
